; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -I include
  -D CORE_DEBUG_LEVEL=1

lib_deps =
  gilmaimon/ArduinoWebsockets @ ^0.5.3
  https://github.com/schreibfaul1/ESP32-audioI2S.git#2.0.6
